### ISSUE TITLE
Database Model for Recommendation

### ISSUE THREAD

**Issue by oyster14** [CSCI-GA-2820-FA23-001/recommendations#5]
**As a** Database maintainer
**I need** a well-structured scheme of recommendations
**So that** the recommendation relationships are clearly posed and efficiently stored

 ### Details and Assumptions
All id-related should be uuid/integer that serve as Unique identifier 

 #### Item Table (need to cooperate with the "Products" team)
 * (primary key) `item_id` Unique identifier 
 * `item_name` **VARCHAR** - Name of the item.
 * `item_price` **FLOAT** - Price of the item.
 * (foreign key)`category_id` - Reference to the Item Category table.
 * `in_stock`: **BOOLEAN** - Whether the item is in stock.
 * `created_at`: **TIMESTAMP**
 * `updated_at`: **TIMESTAMP**
 
 #### Item Category table:
* (primary key) `category_id`: Unique identifier
* `category_name`: **VARCHAR** - Name of the category.

 #### Recommendation Table:
 * (primary key) `recommendation_id`
 * `source_item_id`: the original item
 * `target_item_id`: the recommended item
 * `recommendation_type`: **ENUM("up-sell", "cross-sell", "accessory", ...)**
 * `recommendation_weight`: **DECIMAL(0, 1)** the priority of the recommendation to be shown to the user
 * `status`: **ENUM ("valid", "out of stock", "deprecated")** whether the recommendation is valid or not
 * `created_at`: **TIMESTAMP**
 * `updated_at`: **TIMESTAMP**
   
 ### Acceptance Criteria  
   
```gherkin
Given a user enter the product page 
When the recommendation API is called,
We need to join recommendation tables that has `source_item_id` same as the `item_id`
so that all recommendations from the item is retrieved from database
```

**Comment by yihaozhong** [comment]
Thank you! Here are some improvements I suggest for a more generic use case. 

**1. Timestamps**
`created-at`: Datetime when the recommendation is created/items were added.
`updated-at`: Datetime to track when a recommendation was made or modified

**2. Validity**
Instead of just a Boolean valid, you could use an status ENUM field that allows for multiple states like "Valid", "Out of Stock", "Deprecated", etc. This gives more flexibility in defining the recommendation's current status.
Suggest a `in_stock`: Boolean

**3. Stock Status Dependency**
You mentioned that when the target item is out of stock, the recommendation should be invalid. But there’s no field in the 'Item' table that mentions whether an item is in stock or not.
Suggest `status`: ENUM (Valid, Out of Stock, Deprecated)
